### PR TITLE
Dey/latest updates

### PR DESCRIPTION
**Pull request by shreyadey23**
Vehicle Blueprint and vehicle addition UI updated.

* CARLA version: 0.9.12

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/traffic-generation-editor/21)

### CODE REVIEW

**Review by fabianoboril — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/traffic-generation-editor/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shreyadey23)

**Review by fabianoboril — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/traffic-generation-editor/21)* status: all files reviewed, 1 unresolved discussion (waiting on @shreyadey23)

___
*[osc_generator/add_vehicles.py, line 423 at r1](https://reviewable.io/reviews/carla-simulator/traffic-generation-editor/21#-MkqwI2f6tUv5oXFC_rZ:-MkqwI2f6tUv5oXFC_r_:bk8nr4w) ([raw file](https://github.com/carla-simulator/traffic-generation-editor/blob/5f69d7e0a81bbe916564213729b3a95730b0a7a5/osc_generator/add_vehicles.py#L423)):*
> ```Python
>                         "Volkswagen T2": "vehicle.volkswagen.t2",
>                         "Yamaha YZF": "vehicle.yamaha.yzf",
>                         "Firetruck": "vehicle.carlamotors.firetruck",
> ```

I wonder if we should not have both lists, with an indication of CARLA version, e.g.
BMW Isetta (CARLA 0.9.11): "vehicle.bmw.isetta"
BMW isetta (CARLA 0.9.12): "vehicle.micro.microlino"

**Comment by shreyadey23** [comment]
___
*[osc_generator/add_vehicles.py, line 423 at r1](https://reviewable.io/reviews/carla-simulator/traffic-generation-editor/21#-MkqwI2f6tUv5oXFC_rZ:-MkrXtey7PHj9x75qIBF:b-dae3zf) ([raw file](https://github.com/carla-simulator/traffic-generation-editor/blob/5f69d7e0a81bbe916564213729b3a95730b0a7a5/osc_generator/add_vehicles.py#L423)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

I wonder if we should not have both lists, with an indication of CARLA version, e.g.
BMW Isetta (CARLA 0.9.11): "vehicle.bmw.isetta"
BMW isetta (CARLA 0.9.12): "vehicle.micro.microlino"
</blockquote></details>

Will add the blueprint according to CARLA versions

**Review by fabianoboril — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/traffic-generation-editor/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shreyadey23)

**Pull request merged**
